### ISSUE TITLE
Non-Subsampled_Shearlet_Transform/Form_NSST/Form_Empty/MatlabFuncs.cpp

### ISSUE THREAD

**Issue by zhanghaoqi0914** [fbasatemur/Non-Subsampled_Shearlet_Transform#1]
Hello, where can I get the corresponding matlab function in Non-Subsampled_Shearlet_Transform.

**Comment by fbasatemur** [comment]
Hello, we do not own the Matlab code. I can't share because of that,
sorry. However, you can use the "NsstDec1e ()" function in C ++ code for
NSST.

zhanghaoqi0914 <notifications@github.com>, 10 Şub 2021 Çar, 17:40 tarihinde
şunu yazdı:

**Comment by uzunb** [comment]
Hello, there is no direct corresponding function in matlab. 
If you can't implement this algorithm, you should request to matlab version  from developers of algorithm.

**Comment by uzunb** [comment]
Matlab Code contributors: Glenn R. Easley, Demetrio Labate, and Wang-Q Lim.

**Comment by zhanghaoqi0914** [comment]
> Hello, there is no direct corresponding function in matlab.
> If you can't implement this algorithm, you should request to matlab version from developers of algorithm.

Hello, I want to ask MatlabFuncs.cpp Where can I find the corresponding matlab code.

**Comment by uzunb** [comment]
> Hello, I want to ask MatlabFuncs.cpp Where can I find the corresponding matlab code.

We converted to C++ code from according to docummentations of matlab code. Which of these functions do you want to know about?

**Comment by zhanghaoqi0914** [comment]
Hello, I am using matlab code to generate shearlet filter function(shearing_filters_Myer.m) and compare with your C + + code(Matrix* ShearingFiltersMyer). As shown in the figure below, the code in the red box of MATLAB is not consistent with the C + + code, so I want to know if we are using the same version of matlab code? This link is the corresponding page of shearlab that I use.(http://shearlab.org/files/software/WinMac64_ShearLab-1.1.zip)  I would appreciate it if you could tell me！
![shearlet_filter_matlab](https://user-images.githubusercontent.com/41884656/107846122-445cbc80-6e1c-11eb-98cc-f97371cbc387.png)
<img width="830" alt="shearlet_filter_c++" src="https://user-images.githubusercontent.com/41884656/107846127-4a529d80-6e1c-11eb-8667-83849c54a1dc.png">

**Comment by uzunb** [comment]
It seem different version. We used from our version same matlab code. There not our used version in shearlab.org.

**Comment by zhanghaoqi0914** [comment]
Hello, where can I get your version of matlab code?This is my email, can you send it to me? Thank you very much.（1354422686@qq.com）
